tools/make/launch_cairo_files.py
=> 🧱 output profiling to /build/profiling

docs/supported_curves.md
=> 📝 update use cases

.gitignore, Makefile, readme.txt, requirements.txt, tests/python_tests/add_mod_poly_extensive_test.py, tools/make/cython.sh, tools/make/setup.py, tools/make/setup.sh, tools/make/setup_mac_env.sh, tools/py/add_mod_poly.py, tools/py/add_mod_poly_c.pyx, tools/py/mul_mod_poly.py, tools/py/polynome.pyx
related to #7 
lacks full Cairo translation of the Cython code
and edge case handling a=b=P, a+b=2P 
except that algo is correct
automatic mac support in makefile for cython code and parallelisation thanks to @0xflo-tez
=> Polynomial modular addition research implementation and testing

README.md
Adds attribution to Nethermind in the acknowledgment section.
=> Add attribution for Nethermind's optimised math library

.gitignore, tools/parser_go/README.md, tools/parser_go/example.txt, tools/parser_go/main.go
Add field operation for e6 and 12
Tower operation limited to e2 
Issue Number: #25
Specify the field tower as a CLI arg to select the field for operations
Only improves testing using Cairo hints
=> Feat-go-commands

.gitignore, src/fq.cairo, src/towers/e12.cairo, src/towers/e2.cairo, src/towers/e6.cairo, src/u255.cairo, src/uint256_improvements.cairo, src/utils.cairo, tests/cairo_programs/full_mul.cairo, tests/cairo_programs/uint256_blasted.cairo, tests/protostar_tests/test_e12.cairo, tests/protostar_tests/test_e2.cairo, tools/make/launch_cairo_files.py
=> random add ok

src/fq.cairo, src/towers/e12.cairo, src/towers/e2.cairo, src/towers/e6.cairo, tests/protostar_tests/test_e12.cairo, tests/protostar_tests/test_e2.cairo, tests/protostar_tests/test_e6.cairo, tools/parser_go/main.go
=> ✨ add e2 e6 e12 OK

src/fq.cairo, src/towers/e12.cairo, src/towers/e2.cairo, src/towers/e6.cairo, tests/protostar_tests/test_e12.cairo, tests/protostar_tests/test_e2.cairo, tests/protostar_tests/test_e6.cairo, tools/parser_go/main.go
=> Try e2 mul

src/fq.cairo, src/towers/e2.cairo
=> 🐛 fix sub e2 => fix mul e2

tests/cairo_programs/final_exp.cairo, tools/parser_go/main.go
=> update tests - fix final exponentiation parsing from Gnark

src/bn254/fq.cairo, src/bn254/g1.cairo, src/bn254/g2.cairo, src/bn254/pairing.cairo, src/bn254/pairing_multi.cairo, src/bn254/towers/e12.cairo, src/bn254/towers/e2.cairo, tests/cairo_programs/miller_loop.cairo, tests/protostar_tests/test_pair.cairo, tools/parser_go/bn254/pairing.go
Fix miller and improve speed. More to come
=> Faster pairing

src/bn254/towers/e12.cairo, src/bn254/towers/e2.cairo, tests/protostar_tests/test_e2.cairo
=> 🔒️ pure python hints

Makefile, tools/make/launch_cairo_files.py
Now catching the errors of compilation & wrong file name for super efficiency.
=> ✨ Upgrade make run & make run-profile

tools/make/build.sh
=> compiles starknet contracts or cairo programs accordingly

.gitmodules, Makefile, contracts/cairo_bn254/bn254_precompiles.cairo, contracts/cairo_bn254/library.cairo, protostar.toml, src/bn254/g1.cairo, tests/protostar_tests/bn254/test_precompiles.cairo
Closes #56 
Added upgradable contract with Ethereum precompiles related to bn254:
- ecAdd
- ecMul
- ecPairing
=> Bn254 precompiles

src/bls12_381/fq.cairo
fixes #74 
thank you @onurinanc
=> 🐛 fix 4th limb checks in fq bls

README.md, src/bn254/fq.cairo, src/bn254/g1.cairo, src/bn254/g2.cairo, src/bn254/pairing.cairo, src/bn254/towers/e12.cairo, src/bn254/towers/e2.cairo, src/bn254/towers/e6.cairo
continue improving #48 
fix security issues
=> security & perf improvements

src/bn254/towers/e12.cairo, src/bn254/towers/e2.cairo, src/bn254/towers/e6.cairo
unreduced ops + new benchmarks (2-3%) miller loop improvement
=> e12:: mul_by01234, mul_034_by_034 optimisation

src/ec_ops.cairo, src/precompiled_circuits/all_circuits.py, src/precompiled_circuits/ec.cairo, src/precompiled_circuits/ec.py, src/utils.cairo
Fix some comments
Include scalars in hashing
Check Q_low, Q_high, Q_high_shifted are on curve
=> Ecip Fixes

tools/make/setup.sh
=> Enhance setup verbosity and checks

hydra/garaga/hints/ecip.py, tools/garaga_rs/src/ecip/core.rs, tools/garaga_rs/src/ecip/ff.rs, tools/garaga_rs/src/ecip/polynomial.rs, tools/garaga_rs/src/ecip/rational_function.rs
Add more mul traits and avoid some cloning.
=> Polynomial.rs improvements

.github/workflows/maturin.yml
=> revert to token

hydra/garaga/hints/ecip.py
=> ECIP binding : ensure correct type of passed arguments 

hydra/garaga/modulo_circuit.py
=> Add comment for CairoZero only methods.

hydra/garaga/starknet/groth16_contract_generator/generator.py, src/contracts/groth16_example_bls12_381/src/groth16_verifier.cairo, src/contracts/groth16_example_bn254/src/groth16_verifier.cairo, src/contracts/risc0_verifier_bn254/src/groth16_verifier.cairo, src/src/definitions.cairo
Improve de-serialization using multi_pop_front.
=> Greatly improve deserialization costs (-17% on total steps count of groth16 proof verification)

tools/npm/garaga_ts/src/node/api.ts
- Use nullish coalescing operator (??) instead of logical OR (||) to properly handle false values in options.
- Ensure that user-provided false values for options are respected.
=> fix: Correct default option handling in garaga_ts::msmCalldataBuilder

hydra/garaga/extension_field_modulo_circuit.py
Useful for [garaga zero.](https://github.com/feltroidprime/garaga-zero/tree/main)
=> CairoZero: Update ExtensionFieldModuloCircuit.

docs/gitbook/deploy-your-snark-verifier-on-starknet/groth16/generating-calldata-from-a-proof-and-using-your-deployed-contract/using-python-garaga-cli.md
=> 📝 add calldata method docs

hydra/garaga/starknet/cli/verify.py
Array-formatted calldata should not be serialized: remove the array size prefix.
This way, copy-paste will work with explorers
=> Bug: fix output

docs/gitbook/deploy-your-snark-verifier-on-starknet/noir.md
Guide is amazing. I'd like to spare you from the nittiest of nits. Otherwise, perfect guide!
=> The nittiest nit in the docs

hydra/garaga/starknet/tests_and_calldata_generators/test_writer.py
=>  `make rewrite` takes now 2 sec instead of 18 sec

.github/workflows/docs-sync.yml
=> fix: docs sync CI
